version: "3.8"

services:
  app:
    container_name: django_turbo_app
    build:
      context: ./app/
      dockerfile: Dockerfile
    volumes:
      - ../../:/workspaces
      - ./schema.yaml:/workspaces/django_turbo/sources/backend/schema.yaml
      - ./schema.yaml:/workspaces/django_turbo/sources/frontend/packages/api/schema.yaml
    tty: true
    ports:
      - 8000:8000
      - 3000:3000
      - 3001:3001
    depends_on:
      - db

  db:
    platform: linux/x86_64
    container_name: django_turbo_db
    image: mysql:8.0.28
    ports:
      - 3306:3306
    env_file: ./.env/
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - db_data:/var/lib/mysql
    command: --default_authentication_plugin=mysql_native_password

  mock:
    container_name: django_turbo_mock
    image: stoplight/prism:4
    command: "mock -d -h 0.0.0.0 -p 4010 /tmp/schema.yaml"
    tty: true
    volumes:
      - ./schema.yaml:/tmp/schema.yaml
    ports:
      - 4010:4010

  web:
    container_name: django_turbo_web
    build:
      context: ./web/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/uwsgi_params:/etc/nginx/uwsgi_params
      - ../../:/workspaces
    depends_on:
      - app

  # TODO: https-portal

volumes:
  db_data:
