/* eslint-disable */

/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type BookCreate = {
  /**
   * @maxLength 100
   */
  title?: string | null;
  /**
   * @maximum 2147483647
   * @minimum -2147483648
   */
  price?: number;
};
